### ISSUE TITLE
Tutorial Request

### ISSUE THREAD

**Issue by rodney528** [deadlyjack/acode-plugin-github#7]
Can there be a tutorial or smth because I have no idea how to clone a repo or anything. Like I see the commands... but idk how to use them at all as I'm very new to acode.

**Comment by UnschooledGamer** [comment]
> Can there be a tutorial or smth because I have no idea how to clone a repo or anything. Like I see the commands... but idk how to use them at all as I'm very new to acode.

As of current Date, the plugin doesn't clone the repo but instead it stays in sync with the upstream(GitHub repo) so once you open the repo with Open repo command and make changes it shows a popup for commit message to commit/push the changes to the GitHub repo

**Comment by Artemon1289** [comment]
I think we need help.
Some commands in the plugin page do not help. 
What exactly do I need to text and where?
(I try to text "github"/"github open" etc to the console, but only get an error
"Github is not definedReferenceErrorstack:...message:Github is not defined__proto__:..."
If I can't clone full repo, how do I need to work with that plugin?
Please do a tutorial, better with images or video, and put a link on it to the plugin page in the Acode.
It is not obvious how to work with that plugin
Thanks

**Comment by UnschooledGamer** [comment]
> I think we need help.
> Some commands in the plugin page do not help. 
> What exactly do I need to text and where?
> (I try to text "github"/"github open" etc to the console, but only get an error
> "Github is not definedReferenceErrorstack:...message:Github is not defined__proto__:..."
> If I can't clone full repo, how do I need to work with that plugin?
> Please do a tutorial, better with images or video, and put a link on it to the plugin page in the Acode.
> It is not obvious how to work with that plugin
> Thanks

You have to use those commands in the command palette

**Comment by Artemon1289** [comment]
What do I need to do to get a command palette?
Do I need to install some other plugin?
Can u bring a complete example of the process to get my code file from my github repo?
Please, sorry if this is too simple, but I try to understand.
I just downloaded the Acode yet

**Comment by UnschooledGamer** [comment]
> What do I need to do to get a command palette?
> Do I need to install some other plugin?
> Can u bring a complete example of the process to get my code file from my github repo?
> Please, sorry if this is too simple, but I try to understand.
> I just downloaded the Acode yet

1. Press `ctrl` + `shift` + `p` that opens the 
2. command palette.
3. Type **Open Repository**
4. Click/Select that and Follow the steps that get displayed.

**Comment by Artemon1289** [comment]
What do I need to do to get a command palette?
Do I need to install some other plugin?
Can u bring a complete example of the process to get my code file from my github repo?
Please, sorry if this is too simple, but I try to understand.
I just downloaded the Acode yet

**Comment by Artemon1289** [comment]
Oh, now I understand. Thank you!
Can I open it without an external keyboard?
